services:
  - name: bulk-instagram-post-downloader
    type: web
    runtime: python
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: development
    startCommand: flask run --host=0.0.0.0 --port=5000
